CREATE TABLE roles(
 name varchar(255) NOT NULL,
 enable TINYINT DEFAULT 1 NOT NULL,
 id int UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
 updated_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;